# ARRAYS
    PHP takes this definition a step further, forgoing the requirement that the items share the same data type. 
        For example, an array could quite possibly contain items such as state names, ZIP codes, exam scores, or playing card suits. Each item consists of two components: the aforementioned key and a value. The key serves as the lookup facility for retrieving its counterpart, the value. Keys can be numerical or associative. Numerical keys bear no real relation to the value other than the value’s position in the array.
            $states = array(0 => "Alabama", 1 => "Alaska"...49 => "Wyoming");
            $states = array("OH" => "Ohio", "PA" => "Pennsylvania", "NY" => "New York")
            
    # Creating an Array
        Unlike other languages, PHP doesn’t require that you assign a size to an array at creation time. In fact, because it’s a loosely typed language, PHP doesn’t even require that you declare the array before using it.
            $state[0] = "Delaware";
            Interestingly, if you intend for the index value to be numerical and ascending, you can omit the index value at creation time:
            $state[] = "Pennsylvania";
            $state[] = "New Jersey";
            ...
            $state[] = "Hawaii";
            
        # Creating Arrays with array()
            The array() construct takes as its input zero or more items and returns an array consisting of these input elements. Its prototype looks like this:
                array array([item1 [,item2 ... [,itemN]]])
                Extracting Arrays with list()
            The list() construct is similar to array(), though it’s used to make simultaneous variable assignments from values extracted from an array in just one operation.
            Its prototype looks like this:
                void list(mixed...)
                This construct can be particularly useful when you’re extracting information from a database or file.  
    
        # Populating Arrays with a Predefined Value Range
            The range() function provides an easy way to quickly create and fill an array consisting of a range of low and high integer values.
            An array containing all integer values in this range is returned. Its prototype looks like this:
                array range(int low, int high [, int step])
            For example, suppose you need an array consisting of all possible face values of a die:
                $die = range(1, 6);
                // Same as specifying $die = array(1, 2, 3, 4, 5, 6)
        
        # Testing for an Array
            When you incorporate arrays into your application, you’ll sometimes need to know whether a particular variable is an array. A builtin function, is_array(), is available for accomplishing this task.
            Its prototype follows
                boolean is_array(mixed variable)
            The is_array() function determines whether variable is an array, returning TRUE if it is and FALSE otherwise.
            An example follows:
                $states = array("Florida");
                $state = "Ohio";
                printf("\$states is an array: %s <br />", (is_array($states) ? "TRUE" : "FALSE"));
                printf("\$state is an array: %s <br />", (is_array($state) ? "TRUE" : "FALSE"));
        
            Executing this example produces the following:
                $states is an array: TRUE
                $state is an array: FALSE
            
    # Outputting an Array
        The most common way to output an array’s contents is by iterating over each key and echoing the corresponding value. For instance, a foreach statement does the trick nicely:
            $states = array("Ohio", "Florida", "Texas"); foreach ($states AS $state) {
            echo "{$state}<br />";
            }
            
        # Printing Arrays for Testing Purposes
            The array contents in most of the previous examples have been displayed using comments. While this works great for instructional purposes, in the real world you’ll need to know how to easily output their contents to the screen for testing purposes. This is most commonly done with the print_r() function.
            Its prototype follows:
                boolean print_r(mixed variable [, boolean return])
            The print_r() function accepts a variable and sends its contents to standard output, returning TRUE on success and FALSE otherwise.
    
        # Adding and Removing Array Elements
            PHP provides a number of functions for both growing and shrinking an array. Some of these functions are provided as a convenience to programmers who wish to mimic various queue implementations (FIFO, LIFO, etc.), as reflected by their names (push, pop, shift, and unshift).
            Adding a Value to the Front of an Array
            The array_unshift() function adds elements to the front of the array. All preexisting numerical keys are modified to reflect their new position in the array, but associative keys aren’t affected.
            Its prototype follows:
                int array_unshift(array array, mixed variable [, mixed variable...])
            The following example adds two states to the front of the $states array:
                $states = array("Ohio", "New York"); array_unshift($states, "California", "Texas");
                // $states = array("California", "Texas", "Ohio", "New York");
            Adding a Value to the End of an Array
            The array_push() function adds a value to the end of an array, returning the total count of elements in the array after the new value has been added. You can push multiple variables onto the array simultaneously by passing these variables into the function as input parameters.
            Its prototype follows:
                int array_push(array array, mixed variable [, mixed variable...])
            The following example adds two more states onto the $states array:
                $states = array("Ohio", "New York"); array_push($states, "California", "Texas");
                // $states = array("Ohio", "New York", "California", "Texas");
            Removing a Value from the Front of an Array
            The array_shift() function removes and returns the first item found in an array. If numerical keys are used, all corresponding values will be shifted down, whereas arrays using associative keys will not be affected.
            Its prototype follows
                mixed array_shift(array array)
            The following example removes the first state from the $states array:
                $states = array("Ohio", "New York", "California", "Texas");
                $state = array_shift($states);
                // $states = array("New York", "California", "Texas")
                // $state = "Ohio"
            Removing a Value from the End of an Array
            The array_pop() function removes and returns the last element from an array. Its prototype follows:
                mixed array_pop(array array)
            The following example removes the last state from the $states array:
                $states = array("Ohio", "New York", "California", "Texas");
                $state = array_pop($states);
                // $states = array("Ohio", "New York", "California"
                // $state = "Texas"
            
    # Locating Array Elements
        The ability to efficiently sift through data is absolutely crucial in today’s information-driven society.
        |-------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
        | Searching an Array                  | The in_array() function searches an array for a specific value, returning TRUE if the value is found and FALSE otherwise. Its prototype follows:  boolean in_array(mixed needle, array haystack [, boolean strict])  |
        | Searching Associative Array Keys    | The function array_key_exists() returns TRUE if a specified key is found in an array and FALSE otherwise. Its prototype follows: boolean array_key_exists(mixed key, array array)                                    |
        | Searching Associative Array Values  | The array_search() function searches an array for a specified value, returning its key if located and FALSE otherwise. Its prototype follows: mixed array_search(mixed needle, array haystack [, boolean strict])    |
        | Retrieving Array Keys               | The array_keys() function returns an array consisting of all keys located in an array. Its prototype follows: array array_keys(array array [, mixed search_value [, boolean preserve_keys]])                         |
        | Retrieving Array Values             | The array_values() function returns all values located in an array, automatically providing numeric indexes for the returned array. Its prototype follows: array array_values(array array)                           |
        |-------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    
    # Traversing Arrays
        The need to travel across an array and retrieve various keys, values, or both is common, so it’s not a surprise that PHP offers numerous functions suited to this need. Many of these functions do double duty: retrieving the key or value residing at the current pointer location, and moving the pointer to the next appropriate location.
            |----------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
            | Retrieving the Current Array Key                   | The key() function returns the key located at the current pointer position of the provided array. Its prototype follows: mixed key(array array)                                                                                     |
            | Retrieving the Current Array Value                 | The current() function returns the array value residing at the current pointer position of the array. Its prototype follows: mixed current(array array)                                                                             |
            | Retrieving the Current Array Key and Value         | The each() function returns the current key/value pair from the array and advances the pointer one position. Its prototype follows: array each(array array)                                                                         |
            | Moving the Array Pointer                           | Several functions are available for moving the array pointer                                                                                                                                                                        |
            | Moving the Pointer to the Next Array Position      | The next() function returns the array value residing at the position immediately following that of the current array pointer. Its prototype follows: mixed next(array array)                                                        |
            | Moving the Pointer to the Previous Array Position  | The prev() function returns the array value residing at the location preceding the current pointer location, or FALSE if the pointer resides at the first position in the array. Its prototype follows: mixed prev(array array)     |
            | Moving the Pointer to the First Array Position     | The reset() function serves to set an array pointer back to the beginning of the array. Its prototype follows: mixed reset(array array)                                                                                             |
            | Moving the Pointer to the Last Array Position      | The end() function moves the pointer to the last position of an array, returning the last element. Its prototype follows: mixed end(array array)                                                                                    |
            |----------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
        
        # Passing Array Values to a Function
            The array_walk() function will pass each element of an array to the user-defined function. This is useful when you need to perform a particular action based on each array element. If you intend to actually modify the array key/value pairs, you’ll need to pass each key/value to the function as a reference.
            Its prototype follows
                boolean array_walk(array &array, callback function [, mixed userdata])
            Determining Array Size and Uniqueness
            A few functions are available for determining the number of total and unique array values.
                |-----------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
                | Determining the Size of an Array  | The count() function returns the total number of values found in an array. Its prototype follows: integer count(array array [, int mode])                                                                                    |
                | Counting Array Value Frequency    | The array_count_values() function returns an array consisting of associative key/value pairs. Its prototype follows: array array_count_values(array array)                                                                   |
                | Determining Unique Array Values   | The array_unique() function removes all duplicate values found in an array, returning an array consisting of solely unique values. Its prototype follows:  array array_unique(array array [, int sort_flags = SORT_STRING])  |
                |-----------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    
    # Sorting Arrays
        |----------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
        | Reversing Array Element Order                                        | The array_reverse() function reverses an array’s element order. Its prototype follows: array array_reverse(array array [, boolean preserve_keys])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
        | Flipping Array Keys and Values                                       | The array_flip() function reverses the roles of the keys and their corresponding values in an array. Its prototype follows: array array_flip(array array)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
        | Sorting an Array                                                     | The sort() function sorts an array, ordering elements from lowest to highest value. Its prototype follows: void sort(array array [, int sort_flags])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
        | Sorting an Array While Maintaining Key/Value Pairs                   | The asort() function is identical to sort(), sorting an array in ascending order, except that the key/value correspondence is maintained. Its prototype follows: void asort(array array [, integer sort_flags])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
        | Sorting an Array in Reverse Order                                    | The rsort() function is identical to sort(), except that it sorts array items in reverse (descending) order.Its prototype follows: void rsort(array array [, int sort_flags])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
        | Sorting an Array in Reverse Order While Maintaining Key/Value Pairs  | Like asort(), arsort() maintains key/value correlation. However, it sorts the array in reverse order. Its prototype follows: void arsort(array array [, int sort_flags])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
        | Sorting an array Naturally                                           | The natsort() function is intended to offer a sorting mechanism comparable to the mechanisms that people normally use. Its prototype follows:void natsort(array array)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | 
        | Case-Insensitive Natural Sorting                                     | The function natcasesort() is functionally identical to natsort(), except that it is case insensitive: void natcasesort(array array)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 
        | Sorting an Array by Key Values                                       | The ksort() function sorts an array by its keys, returning TRUE on success and FALSE otherwise. Its prototype follows: integer ksort(array array [, int sort_flags])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
        | Sorting Array Keys in Reverse Order                                  | The krsort() function operates identically to ksort(), sorting by key, except that it sorts in reverse (descending) order. Its prototype follows: integer krsort(array array [, int sort_flags])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
        | Sorting According to User-Defined Criteria                           | The usort() function offers a means for sorting an array by using a user-defined comparison algorithm, embodied within a function. This is useful when you need to sort data in a fashion not offered by one of PHP’s built-in sorting functions. Its prototype follows: void usort(array array, callback function_name)                                                                                                                                                                                                                                                                                                                                                                                        |
        | -------------------------------------------Merging, Slicing, Splicing, and Dissecting Arrays-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
        | Merging Arrays                                                       | The array_merge() function merges arrays together, returning a single, unified array. The resulting array will begin with the first input array parameter, appending each subsequent array parameter in the order of appearance. Its prototype follows:  array array_merge(array array1, array array2 [, array arrayN])                                                                                                                                                                                                                                                                                                                                                                                         |
        | Recursively Appending Arrays                                         | The array_merge_recursive() function operates identically to array_merge(), joining two or more arrays together to form a single, unified array. The difference between the two functions lies in the way that this function behaves when a string key located in one of the input arrays already exists within the resulting array. Note that array_merge() will simply overwrite the preexisting key/value pair, replacing it with the one found in the current input array, while array_merge_recursive() will instead merge the values together, forming a new array with the preexisting key as its name. Its prototype follows: array array_merge_recursive(array array1, array array2 [, array arrayN])  |
        | Combining Two Arrays                                                 | The array_combine() function produces a new array consisting of a submitted set of keys and corresponding values. Its prototype follows: array array_combine(array keys, array values) Both input arrays must be of equal size, and neither can be empty                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
        | Slicing an Array                                                     | The array_slice() function returns a section of an array based on a starting and ending offset value. Its prototype follows: array array_slice(array array, int offset [, int length [, boolean preserve_keys]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
        | Splicing an Array                                                    | The array_splice() function removes all elements of an array found within a specified range, returning those removed elements in the form of an array. Its prototype follows: array array_splice(array array, int offset [, int length [, array replacement]])                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
        | Calculating an Array Intersection                                    | The array_intersect() function returns a key-preserved array consisting only of those values present in the first array that are also present in each of the other input arrays. Its prototype follows: array array_intersect(array array1, array array2 [, arrayN])  Calculating Associative Array Intersections  The function array_intersect_assoc() operates identically to array_intersect(), except that it also considers array keys in the comparison. Therefore, only key/value pairs located in the first array that arealso found in all other input arrays will be returned in the resulting array. Its prototype follows: array array_intersect_assoc(array array1, array array2 [, arrayN])       |
        | Calculating Array Differences                                        | Essentially the opposite of array_intersect(), the function array_diff() returns those values located in the first array that are not located in any of the subsequent arrays: array array_diff(array array1, array array2 [, arrayN])                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
        | Calculating Associative Array Differences                            | The function array_diff_assoc() operates identically to array_diff(), except that it also considers array keys in the comparison. Therefore, only key/value pairs located in the first array but not appearing in any of the other input arrays will be returned in the result array. Its prototype follows: array array_diff_assoc(array array1, array array2 [, array arrayN])                                                                                                                                                                                                                                                                                                                                |
        |----------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
 
 
